name = "activa_agent"
description = "The assessment hosting agent for tau-bench."
version = "0.1.0"

defaultInputModes = ["text"]
defaultOutputModes = ["text"]
[capabilities]
streaming = false

[[skills]]
id = "host_assess_tau_bench"
name = "Tau-bench assessment hosting"
description = """
Assess the tool-calling ability of an agent.
"""
tags = ["activa agent", "assessment hosting", "tau-bench"]
examples = ["""    
Your task is to instantiate tau-bench to test the agent located at:
<activa_agent_url>
http://localhost:9002/
</activa_agent_url>
You should use the following env configuration:
<run_config>
{
  "domain": "retail",
  "task_ids": ["1"],
  "max_steps": 100,
  "user_llm": "gemini/gemini-pro",
  "user_llm_args": {
    "temperature": 0.0
  }
}
</run_config>
    """]
